version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.4
    working_directory: /go/src/github.com/candid82/joker
    steps:
      - checkout
      - run:
          name: go get readline
          command: go get -d -v github.com/chzyer/readline
      - run:
          name: go get profile
          command: go get -d -v github.com/pkg/profile
      - run:
          name: go get yaml
          command: go get -d -v gopkg.in/yaml.v2
      - run:
          name: go generate
          command: go generate -v ./...
      - run:
          name: go build
          command: go build -v github.com/candid82/joker
      - run:
          name: linter tests
          command: ./linter-tests.sh
      - run:
          name: flag tests
          command: ./flag-tests.sh
      - run:
          name: eval tests
          command: ./eval-tests.sh
